version: "3.9"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB=postgres
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      POSTGRES_NAME=postgres
      POSTGRES_USER=postgres
      POSTGRES_PASSWORD=postgres
    depends_on:
      - db